In [2]:
import environ
import gspread
from sqlalchemy import create_engine
import json


env = environ.Env()

database_url = env.str(
    var="DATABASE_URL",
    default="postgres://postgres:@postgres:5432/postgres"
)
aas=['id', 'company_id', 'user_id', 'done', 'type','reference_type', 'reference_id', 
                 'conference_meeting_client', 'conference_meeting_url', 'due_date', 'due_time', 'duration', 
                 'busy_flag','add_time','marked_as_done_time','last_notification_time',
                 'last_notification_user_id','notification_language_id','subject','public_description',
                'calendar_sync_include_context','location','org_id','person_id','deal_id','lead_id','lead_title',
                'active_flag','update_time','update_user_id','gcal_event_id','google_calendar_id',
                 'google_calendar_etag','source_timezone','rec_rule','rec_rule_extension','rec_master_activity_id',
                'conference_meeting_id','note','created_by_user_id','location_subpremise','location_street_number',
                 'location_route','location_sublocality','location_locality','location_admin_area_level_1',
                 'location_admin_area_level_2','location_country','location_postal_code',
                'location_formatted_address','series','org_name','person_name','deal_title','owner_name',
                     'person_dropbox_bcc','deal_dropbox_bcc','assigned_to_user_id','type_name','file']

In [3]:
# from pipedrive import Pipedrive
import pandas as pd
import gspread
from gspread_dataframe import set_with_dataframe
from pipedrive.client import Client


gc = gspread.service_account(filename="./credentials.json")
engine = create_engine(database_url, echo=False)

In [3]:
# pipedrive = Pipedrive('c70f38803bb436089bce792681cd178e8459c86e')
# ppd = pipedrive.activities(method='GET')

In [5]:
client = Client(domain='https://companydomain.pipedrive.com/')
client.set_api_token('c70f38803bb436089bce792681cd178e8459c86e')
act_data = client.activities.get_all_activities()
act_data = pd.DataFrame(act_data['data'])
# act_data['attendees'] = list(map(lambda x: json.dumps(x), act_data['attendees']))
act_data = act_data[aas]
# act_data = act_data.drop(['attendees'], axis=1)

print(act_data)

# act_data.to_sql('etl_sale_activities', engine, if_exists='replace', index=False)

     id  company_id   user_id   done     type reference_type reference_id  \
0    72     7617199  11611129  False  meeting  calendar-sync         None
1   135     7617199  11611129  False  meeting  calendar-sync         None
2   131     7617199  11611129  False  meeting  calendar-sync         None
3   133     7617199  11611129  False  meeting  calendar-sync         None
4   134     7617199  11611129  False  meeting  calendar-sync         None
..  ...         ...       ...    ...      ...            ...          ...
95  305     7617199  11611129  False  meeting  calendar-sync         None
96  300     7617199  11611129  False  meeting  calendar-sync         None
97   61     7617199  11611129  False  meeting  calendar-sync         None
98  309     7617199  11611129  False  meeting  calendar-sync         None
99  299     7617199  11611129  False  meeting  calendar-sync         None

   conference_meeting_client conference_meeting_url    due_date  ... series  \
0                       None                   None  2020-07-20  ...   None
1                       None                   None  2020-07-20  ...   None
2                       None                   None  2020-07-20  ...   None
3                       None                   None  2020-07-20  ...   None
4                       None                   None  2020-07-20  ...   None
..                       ...                    ...         ...  ...    ...
95                      None                   None  2020-08-19  ...   None
96                      None                   None  2020-08-20  ...   None
97                      None                   None  2020-08-20  ...   None
98                      None                   None  2020-08-21  ...   None
99                      None                   None  2020-08-21  ...   None

   org_name  person_name deal_title      owner_name person_dropbox_bcc  \
0      None         None       None  Sales Tracking               None
1      None         None       None  Sales Tracking               None
2      None         None       None  Sales Tracking               None
3      None         None       None  Sales Tracking               None
4      None         None       None  Sales Tracking               None
..      ...          ...        ...             ...                ...
95     None         None       None  Sales Tracking               None
96     None         None       None  Sales Tracking               None
97     None         None       None  Sales Tracking               None
98     None         None       None  Sales Tracking               None
99     None         None       None  Sales Tracking               None

    deal_dropbox_bcc  assigned_to_user_id type_name  file
0               None             11611129   Meeting  None
1               None             11611129   Meeting  None
2               None             11611129   Meeting  None
3               None             11611129   Meeting  None
4               None             11611129   Meeting  None
..               ...                  ...       ...   ...
95              None             11611129   Meeting  None
96              None             11611129   Meeting  None
97              None             11611129   Meeting  None
98              None             11611129   Meeting  None
99              None             11611129   Meeting  None

[100 rows x 60 columns]

In [5]:
response['additional_data']

{'pagination': {'start': 0,
  'limit': 100,
  'more_items_in_collection': True,
  'next_start': 100}}

In [26]:
url = 'https://docs.google.com/spreadsheets/d/1ab4eW4deYLV-3mMgAMuafoWM3e7JjYzoLDAJ83WPuaA/edit#gid=13444138'
workbook = gc.open_by_url(url)
sheet = workbook.get_worksheet(3)
# set_with_dataframe(sheet, act_data1)

In [7]:
org = client.organizations.get_all_organizations()
actf = org['data']
actf = pd.DataFrame(actf)
# sheetorg = workbook.get_worksheet(4)
# set_with_dataframe(sheetorg, actf)
# actf.head()

In [17]:
deals = client.deals.get_all_deals()
ddata = deals['data']
ddf = pd.DataFrame(ddata)
# sheetdeals = workbook.get_worksheet(5)
# set_with_dataframe(sheetdeals, ddf)
# ddf.head()

In [18]:
t1 = list(ddf['id'])

In [6]:
stage = client.stages.get_all_stages()
dstage = stage['data']
sdf = pd.DataFrame(dstage)
# sheetstage = workbook.get_worksheet(6)
# set_with_dataframe(sheetstage, sdf)
# sdf.head()
sdf.to_sql('etl_sale_stages', engine, if_exists='replace', index=False)

In [11]:
st_deal = client.stages.get_stage_deals(62)
st_deal = pd.DataFrame(st_deal['data'])
# st_deal

In [12]:
se_deal = client.stages.get_stage_deals(2)
se_deal = pd.DataFrame(se_deal['data'])
# se_deal

In [28]:
product = client.products.get_all_products()
product = pd.DataFrame(product['data'])

# sheetstage = workbook.get_worksheet(7)
# set_with_dataframe(sheetstage, product)
producr_id = list(product['id'])
producr_id

[2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
product_list = list()
for i in producr_id:
    pdp = client.products.get_product_deal(str(i))
    if pdp['data']:
        for j in pdp['data']:
            product_list.append({'product_id': i, 'deal_id': j['id']})
product_list = pd.DataFrame(product_list)
product_list

    product_id  deal_id
0            2       94
1            2       64
2            2       25
3            3       94
4            3       64
5            3       25
6            4       94
7            7      243
8            8       64
9            9      243
10          10      319

In [14]:
ddf_re = ddf.rename(columns={'id': 'deal_id'})
product_re = product.rename(columns={'id': 'product_id'})
product_df = product_list.join(product_re.set_index('product_id'), on='product_id')
product_df[['product_id', 'name']]
product_df = product_df.rename(columns={'name':'product_name'})

NameError: name 'ddf' is not defined

In [ ]:
product_df = product_df[['product_id', 'product_name', 'deal_id']]
product_df

In [24]:
col = ['deal_id','creator_user_id','user_id', 'person_id','org_id','stage_id',
           'title','value', 'currency', 'add_time', 'update_time','stage_change_time', 'active', 'deleted', 'status']

In [16]:
# product_df = get_pipedrive_product()
product_df = product_df[['product_id', 'name', 'deal_id']]
deals_data = client.deals.get_all_deals()
deals_data = pd.DataFrame(deals_data['data'])
deals_data['creator_user_id'] = list(map(lambda x: json.dumps(x), deals_data['creator_user_id']))
deals_data['person_id'] = list(map(lambda x: json.dumps(x), deals_data['person_id']))
deals_data['user_id'] = list(map(lambda x: json.dumps(x), deals_data['user_id']))
deals_data['org_id'] = list(map(lambda x: json.dumps(x), deals_data['org_id']))


ddf_re = deals_data.rename(columns={'id': 'deal_id'})
ddf_join = ddf_re.join(product_df.set_index('deal_id'), on='deal_id')

# print(ddf_join)

# ddf_join.to_sql('etl_sale_deals', engine, if_exists='replace', index=False)

NameError: name 'product_df' is not defined

In [10]:
get_deal = client.deals.get_deal(deal_id=100)
get_deals

{'success': True,
 'data': {'id': 100,
  'creator_user_id': {'id': 11611129,
   'name': 'Sales Tracking',
   'email': 'presale@codium.co',
   'has_pic': 0,
   'pic_hash': None,
   'active_flag': True,
   'value': 11611129},
  'user_id': {'id': 11611129,
   'name': 'Sales Tracking',
   'email': 'presale@codium.co',
   'has_pic': 0,
   'pic_hash': None,
   'active_flag': True,
   'value': 11611129},
  'person_id': {'active_flag': True,
   'name': "K'Suthep Saowamas",
   'email': [{'value': '', 'primary': True}],
   'phone': [{'value': '', 'primary': True}],
   'value': 91},
  'org_id': {'name': 'Z.COM',
   'people_count': 1,
   'owner_id': 11611129,
   'address': None,
   'active_flag': True,
   'cc_email': 'codium2@pipedrivemail.com',
   'value': 86},
  'stage_id': 17,
  'title': 'ระบบการจัดการออก Cert SSL',
  'value': 217000,
  'currency': 'THB',
  'add_time': '2020-08-09 08:29:37',
  'update_time': '2021-01-22 04:03:56',
  'stage_change_time': '2021-01-22 04:03:56',
  'active': True,
  'deleted': False,
  'status': 'open',
  'probability': None,
  'next_activity_date': None,
  'next_activity_time': None,
  'next_activity_id': None,
  'last_activity_id': None,
  'last_activity_date': None,
  'lost_reason': None,
  'visible_to': '3',
  'close_time': None,
  'pipeline_id': 3,
  'won_time': None,
  'first_won_time': None,
  'lost_time': None,
  'products_count': 0,
  'files_count': 1,
  'notes_count': 2,
  'followers_count': 1,
  'email_messages_count': 0,
  'activities_count': 0,
  'done_activities_count': 0,
  'undone_activities_count': 0,
  'participants_count': 1,
  'expected_close_date': None,
  'last_incoming_mail_time': None,
  'last_outgoing_mail_time': None,
  'label': None,
  'a3d4fbed73213694cc4df7ba0f8b3f05c4897107': None,
  'cdfa6ffeb55b824fd2a274289bc13b8699324616': None,
  'db12720d8b34f49fd7fc755c447360174f46de78': None,
  'b54d08b1c715a7f528a8d91ff907a14aa1b20161': None,
  'stage_order_nr': 6,
  'person_name': "K'Suthep Saowamas",
  'org_name': 'Z.COM',
  'next_activity_subject': None,
  'next_activity_type': None,
  'next_activity_duration': None,
  'next_activity_note': None,
  'formatted_value': 'THB\xa0217,000',
  'weighted_value': 217000,
  'formatted_weighted_value': 'THB\xa0217,000',
  'weighted_value_currency': 'THB',
  'rotten_time': None,
  'owner_name': 'Sales Tracking',
  'cc_email': 'codium2+deal100@pipedrivemail.com',
  'org_hidden': False,
  'person_hidden': False,
  'average_time_to_won': {'y': 0,
   'm': 0,
   'd': 0,
   'h': 0,
   'i': 0,
   's': 0,
   'total_seconds': 0},
  'average_stage_progress': 0,
  'age': {'y': 0,
   'm': 5,
   'd': 22,
   'h': 19,
   'i': 21,
   's': 56,
   'total_seconds': 15189716},
  'stay_in_pipeline_stages': {'times_in_stages': {'12': 172,
    '13': 14326287,
    '14': 0,
    '15': 0,
    '16': 0,
    '17': 863257},
   'order_of_stages': [12, 13, 14, 15, 16, 17]},
  'last_activity': None,
  'next_activity': None},
 'additional_data': {'dropbox_email': 'codium2+deal100@pipedrivemail.com'},
 'related_objects': {'user': {'11611129': {'id': 11611129,
    'name': 'Sales Tracking',
    'email': 'presale@codium.co',
    'has_pic': 0,
    'pic_hash': None,
    'active_flag': True}},
  'organization': {'86': {'id': 86,
    'name': 'Z.COM',
    'people_count': 1,
    'owner_id': 11611129,
    'address': None,
    'active_flag': True,
    'cc_email': 'codium2@pipedrivemail.com'}},
  'person': {'91': {'active_flag': True,
    'id': 91,
    'name': "K'Suthep Saowamas",
    'email': [{'value': '', 'primary': True}],
    'phone': [{'value': '', 'primary': True}]}}}}

In [24]:
dtest1 = list(ddf['id'])
get_deals_list = list()
for i in dtest1:
    deal_de = client.deals.get_deal(deal_id=int(i))
    get_deals_list.append(deal_de["data"])
gd_pd = pd.DataFrame(get_deals_list)
gd_pd

,id,creator_user_id,user_id,person_id,org_id,stage_id,title,value,currency,add_time,...,owner_name,cc_email,org_hidden,person_hidden,average_time_to_won,average_stage_progress,age,stay_in_pipeline_stages,last_activity,next_activity
0,10,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ยงยุทธ', 'email...","{'name': 'บริษัท วี.เค.จี กรุ๊ป จำกัด', 'peopl...",62,บริษัท วี.เค.จี กรุ๊ป จำกัด,0,THB,2020-07-13 03:35:33,...,Sales Tracking,codium2+deal10@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 0, 'h': 0, 'i': 0, 's': ...",0.00,"{'y': 0, 'm': 6, 'd': 19, 'h': 0, 'i': 41, 's'...","{'times_in_stages': {'1': 14113011, '62': 3428...",None,None
1,11,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ทวี สกุลคุณสวัส...",None,2,ทวี สกุลคุณสวัสดิ์,0,THB,2020-07-13 03:42:29,...,Sales Tracking,codium2+deal11@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 0, 'h': 0, 'i': 0, 's': ...",0.00,"{'y': 0, 'm': 0, 'd': 11, 'h': 3, 'i': 33, 's'...","{'times_in_stages': {'1': 963200, '2': 0}, 'or...",None,None
2,12,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ทิศากร ยูวะเวศ'...","{'name': 'กรมยุทธศึกษาทหารบก', 'people_count':...",62,กรมยุทธศึกษาทหารบก,0,THB,2020-07-13 03:45:53,...,Sales Tracking,codium2+deal12@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 0, 'h': 0, 'i': 0, 's': ...",0.00,"{'y': 0, 'm': 6, 'd': 19, 'h': 0, 'i': 31, 's'...","{'times_in_stages': {'1': 14112390, '62': 3428...","{'id': 139, 'company_id': 7617199, 'user_id': ...",None
3,13,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'สุรัตน์', 'emai...","{'name': 'บริษัท อาบาคัสซึ', 'people_count': 1...",62,บริษัท อาบาคัสซึ,0,THB,2020-07-13 03:53:13,...,Sales Tracking,codium2+deal13@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 0, 'h': 0, 'i': 0, 's': ...",0.00,"{'y': 0, 'm': 6, 'd': 19, 'h': 0, 'i': 23, 's'...","{'times_in_stages': {'1': 14111949, '62': 3428...","{'id': 140, 'company_id': 7617199, 'user_id': ...",None
4,14,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'Warathep Chalad...","{'name': 'SNC FORMER PUBLIC COMPANY LIMITED.',...",62,SNC FORMER PUBLIC COMPANY LIMITED.,0,THB,2020-07-13 04:07:23,...,Sales Tracking,codium2+deal14@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 0, 'h': 0, 'i': 0, 's': ...",0.00,"{'y': 0, 'm': 6, 'd': 19, 'h': 0, 'i': 9, 's':...","{'times_in_stages': {'1': 14111070, '62': 3428...",None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,114,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...",None,"{'name': 'Omsin Bank', 'people_count': 0, 'own...",28,Omsin Bank,0,THB,2020-08-28 03:20:48,...,Sales Tracking,codium2+deal114@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 10, 'h': 8, 'i': 25, 's'...",5.99,"{'y': 0, 'm': 4, 'd': 1, 'h': 3, 'i': 34, 's':...","{'times_in_stages': {'24': 0, '25': 5560, '26'...",None,None
96,115,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'K.Nan', 'email'...","{'name': 'Glico', 'people_count': 0, 'owner_id...",27,Glico,0,THB,2020-08-28 03:22:03,...,Sales Tracking,codium2+deal115@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 10, 'h': 8, 'i': 25, 's'...",5.99,"{'y': 0, 'm': 4, 'd': 20, 'h': 0, 'i': 20, 's'...","{'times_in_stages': {'24': 0, '25': 0, '26': 0...",None,None
97,116,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'K.Nut', 'email'...","{'name': 'Tim Hortons', 'people_count': 0, 'ow...",28,Tim Hortons (Operation),0,THB,2020-08-28 03:22:52,...,Sales Tracking,codium2+deal116@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 10, 'h': 8, 'i': 25, 's'...",5.99,"{'y': 0, 'm': 4, 'd': 1, 'h': 3, 'i': 32, 's':...","{'times_in_stages': {'24': 0, '25': 0, '26': 0...",None,None
98,117,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...",None,"{'name': 'PTT Global Chemical', 'people_count'...",28,PTT,0,THB,2020-08-28 03:23:18,...,Sales Tracking,codium2+deal117@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 10, 'h': 8, 'i': 25, 's'...",5.99,"{'y': 0, 'm': 4, 'd': 1, 'h': 3, 'i': 31, 's':...","{'times_in_stages': {'24': 0, '25': 0, '26': 0...",None,None
99,118,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...",None,"{'name': 'S11', 'people_count': 0, 'owner_id':...",28,S11 Call Center Lending app,0,THB,2020-08-28 03:24:51,...,Sales Tracking,codium2+deal118@pipedrivemail.com,False,False,"{'y': 0, 'm': 0, 'd': 10, 'h': 8, 'i': 25, 's'...",5.99,"{'y': 0, 'm': 4, 'd': 1, 'h': 3, 'i': 29, 's':...","{'times_in_stages': {'24': 0, '25': 0, '26': 1...",None,None

In [29]:
# sheetstage = workbook.get_worksheet(7)
# set_with_dataframe(sheetstage, gd_pd, row=15)

In [110]:
time_stay_stage = gd_pd[['stay_in_pipeline_stages', 'id', 'pipeline_id', 'status']]
time_stay_stage

                              stay_in_pipeline_stages   id  pipeline_id status
0   {'times_in_stages': {'1': 14113011, '62': 3428...   10            1   open
1   {'times_in_stages': {'1': 963200, '2': 0}, 'or...   11            1   lost
2   {'times_in_stages': {'1': 14112390, '62': 3428...   12            1   open
3   {'times_in_stages': {'1': 14111949, '62': 3428...   13            1   open
4   {'times_in_stages': {'1': 14111070, '62': 3428...   14            1   open
..                                                ...  ...          ...    ...
95  {'times_in_stages': {'24': 0, '25': 5560, '26'...  114            5    won
96  {'times_in_stages': {'24': 0, '25': 0, '26': 0...  115            5   lost
97  {'times_in_stages': {'24': 0, '25': 0, '26': 0...  116            5    won
98  {'times_in_stages': {'24': 0, '25': 0, '26': 0...  117            5    won
99  {'times_in_stages': {'24': 0, '25': 0, '26': 1...  118            5    won

[100 rows x 4 columns]

In [116]:
stage_pipeline = {1: [1, 2, 35, 3, 6], 5: [24, 25, 28]}
# time_dict = {}
time_list = []
for idx, row in time_stay_stage.iterrows():
    time_dict = {}
    time_range = row['stay_in_pipeline_stages']['times_in_stages']
    if row['status'] in ['won', 'lost']:
        if row['pipeline_id'] == 1:
            if '2' in time_range.keys():
                meeting_time = time_range['2']
            if '35' in time_range.keys():
                inprocess_time = time_range['35']
            if '3' in time_range.keys() and '6' in time_range.keys():
                won_or_lost_time = time_range['3'] if row['status'] == 'won' else time_range['6']

        elif row['pipeline_id'] == 5:
            if '25' in time_range.keys():
                meeting_time = time_range['25']
            if '65' in time_range.keys():
                inprocess_time = time_range['65']
            if '28' in time_range.keys():
                won_or_lost_time = time_range['28'] if row['status'] == 'won' else None
        else:
            continue

        time_dict['meeting_time'] = meeting_time if meeting_time else None
        time_dict['inprocess_time'] = inprocess_time if inprocess_time else None
        time_dict['won_or_lost_time'] = won_or_lost_time if won_or_lost_time else None
        time_dict['id'] = row['id']
        print(time_dict)
        time_list.append(time_dict)
    
#         print(time_list)

#         print(row['id'], row['stay_in_pipeline_stages'], row['pipeline_id'], row['status'])

{'meeting_time': 2148066, 'inprocess_time': 166303, 'won_or_lost_time': 32, 'id': 30}
{'meeting_time': 10634763, 'inprocess_time': None, 'won_or_lost_time': 21, 'id': 103}
{'meeting_time': 5560, 'inprocess_time': None, 'won_or_lost_time': 10634520, 'id': 114}
{'meeting_time': None, 'inprocess_time': None, 'won_or_lost_time': 10634520, 'id': 115}
{'meeting_time': None, 'inprocess_time': None, 'won_or_lost_time': 10639963, 'id': 116}
{'meeting_time': None, 'inprocess_time': None, 'won_or_lost_time': 10639884, 'id': 117}
{'meeting_time': None, 'inprocess_time': None, 'won_or_lost_time': 10639623, 'id': 118}

In [117]:
time_df = pd.DataFrame(time_list)
time_df
tts = time_stay_stage.merge(time_df, 'inner', on='id')
# tts.drop(columns=[])
sheetstage = workbook.get_worksheet(8)
set_with_dataframe(sheetstage, tts)
tts

,stay_in_pipeline_stages,id,pipeline_id,status,meeting_time,inprocess_time,won_or_lost_time
0,"{'times_in_stages': {'24': 34, '25': 2148066, ...",30,5,won,2148066.0,166303.0,32
1,"{'times_in_stages': {'1': 159, '24': 956589, '...",103,5,lost,10634763.0,NaN,21
2,"{'times_in_stages': {'24': 0, '25': 5560, '26'...",114,5,won,5560.0,NaN,10634520
3,"{'times_in_stages': {'24': 0, '25': 0, '26': 0...",115,5,lost,NaN,NaN,10634520
4,"{'times_in_stages': {'24': 0, '25': 0, '26': 0...",116,5,won,NaN,NaN,10639963
5,"{'times_in_stages': {'24': 0, '25': 0, '26': 0...",117,5,won,NaN,NaN,10639884
6,"{'times_in_stages': {'24': 0, '25': 0, '26': 1...",118,5,won,NaN,NaN,10639623