In [2]:
import environ
import gspread
from sqlalchemy import create_engine
import json


env = environ.Env()

database_url = env.str(
    var="DATABASE_URL",
    default="postgres://postgres:@postgres:5432/postgres"
)

# from pipedrive import Pipedrive
import pandas as pd
import gspread
from gspread_dataframe import set_with_dataframe
from pipedrive.client import Client


gc = gspread.service_account(filename="./credentials.json")
engine = create_engine(database_url, echo=False)
url = 'https://docs.google.com/spreadsheets/d/1ab4eW4deYLV-3mMgAMuafoWM3e7JjYzoLDAJ83WPuaA/'
workbook = gc.open_by_url(url)

In [5]:
client = Client(domain='https://codium2.pipedrive.com/')
client.set_api_token('c70f38803bb436089bce792681cd178e8459c86e')
deals = client.deals.get_all_deals(params={'limit':100000})['data']
df_deals = pd.DataFrame(deals)
df_deals

,id,creator_user_id,user_id,person_id,org_id,stage_id,title,value,currency,add_time,...,next_activity_note,formatted_value,weighted_value,formatted_weighted_value,weighted_value_currency,rotten_time,owner_name,cc_email,org_hidden,person_hidden
0,10,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ยงยุทธ', 'email...","{'name': 'บริษัท วี.เค.จี กรุ๊ป จำกัด', 'peopl...",62,บริษัท วี.เค.จี กรุ๊ป จำกัด,0,THB,2020-07-13 03:35:33,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal10@pipedrivemail.com,False,False
1,11,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ทวี สกุลคุณสวัส...",None,2,ทวี สกุลคุณสวัสดิ์,0,THB,2020-07-13 03:42:29,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal11@pipedrivemail.com,False,False
2,12,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ทิศากร ยูวะเวศ'...","{'name': 'กรมยุทธศึกษาทหารบก', 'people_count':...",62,กรมยุทธศึกษาทหารบก,0,THB,2020-07-13 03:45:53,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal12@pipedrivemail.com,False,False
3,13,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'สุรัตน์', 'emai...","{'name': 'บริษัท อาบาคัสซึ', 'people_count': 1...",62,บริษัท อาบาคัสซึ,0,THB,2020-07-13 03:53:13,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal13@pipedrivemail.com,False,False
4,14,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'Warathep Chalad...","{'name': 'SNC FORMER PUBLIC COMPANY LIMITED.',...",62,SNC FORMER PUBLIC COMPANY LIMITED.,0,THB,2020-07-13 04:07:23,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal14@pipedrivemail.com,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,496,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'นัท', 'email': ...","{'name': 'Alpha electric engineering', 'people...",80,Alpha electric engineering - Jeff,0,THB,2021-03-18 03:27:26,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal496@pipedrivemail.com,False,False
435,497,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ภูริพล สุวลักษณ...","{'name': 'สำนักคอมพิวเตอร์ มหาวิทยาลัยทักษิณ',...",55,สำนักคอมพิวเตอร์ มหาวิทยาลัยทักษิณ - mat/follo...,0,THB,2021-03-18 03:57:25,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal497@pipedrivemail.com,False,False
436,499,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'คุณเสือใหญ่', '...","{'name': 'Tiger Property', 'people_count': 1, ...",55,Tiger Property - แจ้งนัดลูกค้าในไลน์,0,THB,2021-03-18 04:31:27,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal499@pipedrivemail.com,False,False
437,500,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'บอส', 'email': ...","{'name': 'ดีวีเอท DV8', 'people_count': 1, 'ow...",55,ดีวีเอท DV8 - รอลูกค้าส่ง slot,0,THB,2021-03-18 04:58:53,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal500@pipedrivemail.com,False,False
438,501,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'อชิรชญา สงสังข์...","{'name': 'กองช่าง อบต.บานา', 'people_count': 1...",55,กองช่าง อบต.บานา - ไม่ mat / follow up,0,THB,2021-03-18 05:02:02,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal501@pipedrivemail.com,False,False

In [7]:
df_deals.stage_id.dtypes
sheetdeals = workbook.get_worksheet(1)
set_with_dataframe(sheetdeals, df_deals)

In [4]:
df_deals = df_deals[df_deals['pipeline_id'] == 10]
df_deals

,id,creator_user_id,user_id,person_id,org_id,stage_id,title,value,currency,add_time,...,next_activity_note,formatted_value,weighted_value,formatted_weighted_value,weighted_value_currency,rotten_time,owner_name,cc_email,org_hidden,person_hidden
113,138,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ณัฐชยา ปากะบุตร...",None,55,ณัฐชยา ปากะบุตร deal,0,THB,2020-09-28 03:23:10,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal138@pipedrivemail.com,False,False
114,139,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'Rattanaporn Som...",None,55,Rattanaporn Somnoi deal,0,THB,2020-09-28 03:23:48,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal139@pipedrivemail.com,False,False
116,145,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ณมน ดีสุวรรณ', ...",None,55,ณมน ดีสุวรรณ deal,0,THB,2020-09-28 04:25:05,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal145@pipedrivemail.com,False,False
117,147,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'อุทัย เอกนิคม',...","{'name': 'ทำงานอิสระ', 'people_count': 6, 'own...",55,ทำงานอิสระ deal,0,THB,2020-09-28 04:27:46,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal147@pipedrivemail.com,False,False
118,148,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'นายเกรียงไกร สั...","{'name': 'ทำงานอิสระ', 'people_count': 6, 'own...",55,ทำงานอิสระ deal,0,THB,2020-09-28 04:28:48,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal148@pipedrivemail.com,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,494,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'วิชิด จันนุบิน'...","{'name': 'ศรีสยามมงคล(อุดมสุข)', 'people_count...",80,ศรีสยามมงคล(อุดมสุข) - Toon,0,THB,2021-03-16 09:35:43,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal494@pipedrivemail.com,False,False
434,496,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'นัท', 'email': ...","{'name': 'Alpha electric engineering', 'people...",80,Alpha electric engineering - Jeff,0,THB,2021-03-18 03:27:26,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal496@pipedrivemail.com,False,False
435,497,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ภูริพล สุวลักษณ...","{'name': 'สำนักคอมพิวเตอร์ มหาวิทยาลัยทักษิณ',...",55,สำนักคอมพิวเตอร์ มหาวิทยาลัยทักษิณ - mat/follo...,0,THB,2021-03-18 03:57:25,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal497@pipedrivemail.com,False,False
436,498,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'บอส', 'email': ...","{'name': 'ดีวีเอท DV8', 'people_count': 1, 'ow...",55,ดีวีเอท DV8 - รอลูกค้าส่ง slot,0,THB,2021-03-18 04:16:20,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal498@pipedrivemail.com,False,False
437,499,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'คุณเสือใหญ่', '...","{'name': 'Tiger Property', 'people_count': 1, ...",55,Tiger Property - เก็บ requirement,0,THB,2021-03-18 04:31:27,...,None,THB 0,0,THB 0,THB,None,Sales Tracking,codium2+deal499@pipedrivemail.com,False,False

In [5]:
df_deals = df_deals.iloc[:, :26]
df_deals

,id,creator_user_id,user_id,person_id,org_id,stage_id,title,value,currency,add_time,...,next_activity_date,next_activity_time,next_activity_id,last_activity_id,last_activity_date,lost_reason,visible_to,close_time,pipeline_id,won_time
113,138,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ณัฐชยา ปากะบุตร...",None,55,ณัฐชยา ปากะบุตร deal,0,THB,2020-09-28 03:23:10,...,None,None,NaN,NaN,None,ลูกค้าเข้าใจ Product ผิด,3,2020-09-29 08:11:59,10,None
114,139,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'Rattanaporn Som...",None,55,Rattanaporn Somnoi deal,0,THB,2020-09-28 03:23:48,...,None,None,NaN,NaN,None,not the product they thought it was,3,2020-10-01 09:03:08,10,None
116,145,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ณมน ดีสุวรรณ', ...",None,55,ณมน ดีสุวรรณ deal,0,THB,2020-09-28 04:25:05,...,None,None,NaN,NaN,None,ลูกค้าเข้าใจผิด เพราะลูกค้าขายลอตเตอรี่,3,2020-09-30 08:56:59,10,None
117,147,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'อุทัย เอกนิคม',...","{'name': 'ทำงานอิสระ', 'people_count': 6, 'own...",55,ทำงานอิสระ deal,0,THB,2020-09-28 04:27:46,...,None,None,NaN,NaN,None,ลูกค้าเข้าใจผิด คิดว่าเป็นเรื่องกู้ยืม,3,2020-09-30 09:10:48,10,None
118,148,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'นายเกรียงไกร สั...","{'name': 'ทำงานอิสระ', 'people_count': 6, 'own...",55,ทำงานอิสระ deal,0,THB,2020-09-28 04:28:48,...,None,None,NaN,NaN,None,ลูกค้าเข้าใจผิด ปกติเข้าแต่เว็บ คาสิโน,3,2020-09-30 09:18:25,10,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,494,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'วิชิด จันนุบิน'...","{'name': 'ศรีสยามมงคล(อุดมสุข)', 'people_count...",80,ศรีสยามมงคล(อุดมสุข) - Toon,0,THB,2021-03-16 09:35:43,...,None,None,NaN,NaN,None,None,3,None,10,None
434,496,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'นัท', 'email': ...","{'name': 'Alpha electric engineering', 'people...",80,Alpha electric engineering - Jeff,0,THB,2021-03-18 03:27:26,...,None,None,NaN,NaN,None,None,3,None,10,None
435,497,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'ภูริพล สุวลักษณ...","{'name': 'สำนักคอมพิวเตอร์ มหาวิทยาลัยทักษิณ',...",55,สำนักคอมพิวเตอร์ มหาวิทยาลัยทักษิณ - mat/follo...,0,THB,2021-03-18 03:57:25,...,None,None,NaN,NaN,None,None,3,None,10,None
436,498,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'บอส', 'email': ...","{'name': 'ดีวีเอท DV8', 'people_count': 1, 'ow...",55,ดีวีเอท DV8 - รอลูกค้าส่ง slot,0,THB,2021-03-18 04:16:20,...,None,None,NaN,NaN,None,None,3,None,10,None
437,499,"{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'id': 11611129, 'name': 'Sales Tracking', 'em...","{'active_flag': True, 'name': 'คุณเสือใหญ่', '...","{'name': 'Tiger Property', 'people_count': 1, ...",55,Tiger Property - เก็บ requirement,0,THB,2021-03-18 04:31:27,...,None,None,NaN,NaN,None,None,3,None,10,None

In [6]:
deats_stage = df_deals[['stage_id']]
deats_stage = deats_stage.groupby('stage_id')

In [10]:
stages = client.stages.get_all_stages()['data']
df_stages = pd.DataFrame(stages)
# sheetstage = workbook.get_worksheet(2)
# set_with_dataframe(sheetstage, df_stages)
# df_stages

In [23]:
data_lead = pd.read_sql("marketing_lead", engine)
data_lead_time =  data_lead[['id', 'datetime']]
data_lead_time.rename(columns={'id': 'lead_id'}, inplace=True)
data_lead_time

     lead_id                         datetime
0        501 2021-02-19 03:34:46.048972+00:00
1        508        2021-02-19 10:42:23+00:00
2        509        2021-02-20 19:24:00+00:00
3        158        2020-12-01 17:00:00+00:00
4        420 2021-02-08 17:08:30.512920+00:00
..       ...                              ...
356      190        2021-01-08 04:46:00+00:00
357      577        2021-03-07 15:03:09+00:00
358      390        2021-02-02 08:31:24+00:00
359      614 2021-03-11 22:56:45.916646+00:00
360      653        2021-03-17 10:24:08+00:00

[361 rows x 2 columns]

In [19]:
data_pro = pd.read_sql("marketing_prospect", engine)
data_pro

,id,created_at,updated_at,lead_id,deal_id,person_id,org_id
0,4,2021-01-21 04:10:33.697118+00:00,2021-01-21 04:10:33.701544+00:00,275,325,301,268
1,5,2021-01-21 04:33:12.524717+00:00,2021-01-21 04:33:12.524792+00:00,243,326,302,269
2,6,2021-01-21 08:05:54.863000+00:00,2021-01-21 08:05:54.863066+00:00,293,327,303,270
3,7,2021-01-21 08:47:40.404853+00:00,2021-01-21 08:47:40.404918+00:00,297,328,304,271
4,8,2021-01-21 10:31:35.600325+00:00,2021-01-21 10:31:35.600365+00:00,273,329,305,272
...,...,...,...,...,...,...,...
126,134,2021-03-18 03:27:27.000609+00:00,2021-03-18 03:27:27.000678+00:00,653,496,471,437
127,135,2021-03-18 03:57:26.079454+00:00,2021-03-18 03:57:26.079513+00:00,654,497,472,438
128,137,2021-03-18 04:31:28.303752+00:00,2021-03-18 04:31:28.303860+00:00,657,499,474,440
129,138,2021-03-18 04:58:53.847078+00:00,2021-03-18 04:58:53.847113+00:00,658,500,475,441
130,139,2021-03-18 05:02:03.025836+00:00,2021-03-18 05:02:03.025871+00:00,655,501,476,442

In [24]:
data_lead_time = data_lead_time.merge(data_pro, on='lead_id', how='inner')
data_lead_time

,lead_id,datetime,id,created_at,updated_at,deal_id,person_id,org_id
0,509,2021-02-20 19:24:00+00:00,88,2021-02-22 06:30:44.197732+00:00,2021-02-22 06:30:44.197777+00:00,438,414,379
1,512,2021-02-22 09:50:11+00:00,89,2021-02-22 09:51:44.947381+00:00,2021-02-22 09:51:44.947477+00:00,439,415,380
2,514,2021-02-23 04:32:50+00:00,90,2021-02-23 04:35:54.293098+00:00,2021-02-23 04:35:54.293176+00:00,441,417,382
3,507,2021-02-19 10:12:38+00:00,87,2021-02-19 10:27:46.656101+00:00,2021-02-19 10:27:46.656173+00:00,435,411,376
4,506,2021-02-19 09:22:38+00:00,86,2021-02-19 09:25:27.048737+00:00,2021-02-19 09:25:27.048792+00:00,434,410,375
...,...,...,...,...,...,...,...,...
126,329,2021-01-27 09:02:48+00:00,22,2021-01-27 09:47:54.660703+00:00,2021-01-27 09:47:54.660796+00:00,345,321,288
127,401,2021-02-04 00:27:25+00:00,48,2021-02-04 03:37:07.921158+00:00,2021-02-04 03:37:07.921195+00:00,372,348,315
128,577,2021-03-07 15:03:09+00:00,113,2021-03-08 06:04:59.978654+00:00,2021-03-08 06:04:59.978687+00:00,472,447,413
129,390,2021-02-02 08:31:24+00:00,42,2021-02-02 09:41:04.457437+00:00,2021-02-02 09:41:04.457485+00:00,365,341,308
130,653,2021-03-17 10:24:08+00:00,134,2021-03-18 03:27:27.000609+00:00,2021-03-18 03:27:27.000678+00:00,496,471,437

In [28]:
tt = client.deals.get_deal_details(deal_id=468)
tt['data']

{'id': 468,
 'creator_user_id': {'id': 11611129,
  'name': 'Sales Tracking',
  'email': 'presale@codium.co',
  'has_pic': 0,
  'pic_hash': None,
  'active_flag': True,
  'value': 11611129},
 'user_id': {'id': 11611129,
  'name': 'Sales Tracking',
  'email': 'presale@codium.co',
  'has_pic': 0,
  'pic_hash': None,
  'active_flag': True,
  'value': 11611129},
 'person_id': {'active_flag': True,
  'name': 'คุณ สุรชัย',
  'email': [{'label': 'work', 'value': 'admin@pusoft.co.th', 'primary': True}],
  'phone': [{'label': '', 'value': '0970122481', 'primary': True}],
  'value': 443},
 'org_id': {'name': 'PU Soft',
  'people_count': 1,
  'owner_id': 11611129,
  'address': None,
  'active_flag': True,
  'cc_email': 'codium2@pipedrivemail.com',
  'value': 409},
 'stage_id': 61,
 'title': 'PU Soft - Toon #1 ไม่สนใจ',
 'value': 0,
 'currency': 'THB',
 'add_time': '2021-03-05 09:49:31',
 'update_time': '2021-03-18 08:28:27',
 'stage_change_time': '2021-03-08 04:21:06',
 'active': True,
 'deleted': False,
 'status': 'open',
 'probability': None,
 'next_activity_date': None,
 'next_activity_time': None,
 'next_activity_id': None,
 'last_activity_id': None,
 'last_activity_date': None,
 'lost_reason': None,
 'visible_to': '3',
 'close_time': None,
 'pipeline_id': 10,
 'won_time': None,
 'first_won_time': None,
 'lost_time': None,
 'products_count': 0,
 'files_count': 0,
 'notes_count': 2,
 'followers_count': 1,
 'email_messages_count': 0,
 'activities_count': 0,
 'done_activities_count': 0,
 'undone_activities_count': 0,
 'participants_count': 1,
 'expected_close_date': None,
 'last_incoming_mail_time': None,
 'last_outgoing_mail_time': None,
 'label': None,
 'a3d4fbed73213694cc4df7ba0f8b3f05c4897107': '15',
 'cdfa6ffeb55b824fd2a274289bc13b8699324616': None,
 'db12720d8b34f49fd7fc755c447360174f46de78': None,
 'b54d08b1c715a7f528a8d91ff907a14aa1b20161': None,
 'renewal_type': 'one_time',
 'd25eed5492b16b35a856444f2a9663c1c0261584': '37',
 '322d77c1eb7f3a30eac9d35c874cace212959cec': 50000,
 '322d77c1eb7f3a30eac9d35c874cace212959cec_currency': 'THB',
 '583b1978a81b12771c0ba83ae6fbe088d7edd11f': 10000,
 '583b1978a81b12771c0ba83ae6fbe088d7edd11f_currency': 'THB',
 'stage_order_nr': 2,
 'person_name': 'คุณ สุรชัย',
 'org_name': 'PU Soft',
 'next_activity_subject': None,
 'next_activity_type': None,
 'next_activity_duration': None,
 'next_activity_note': None,
 'formatted_value': 'THB\xa00',
 'weighted_value': 0,
 'formatted_weighted_value': 'THB\xa00',
 'weighted_value_currency': 'THB',
 'rotten_time': None,
 'owner_name': 'Sales Tracking',
 'cc_email': 'codium2+deal468@pipedrivemail.com',
 'org_hidden': False,
 'person_hidden': False,
 'average_time_to_won': {'y': 0,
  'm': 0,
  'd': 0,
  'h': 0,
  'i': 0,
  's': 0,
  'total_seconds': 0},
 'average_stage_progress': 0,
 'age': {'y': 0,
  'm': 0,
  'd': 12,
  'h': 22,
  'i': 42,
  's': 44,
  'total_seconds': 1118564},
 'stay_in_pipeline_stages': {'times_in_stages': {'55': 239495, '61': 879069},
  'order_of_stages': [55, 61]},
 'last_activity': None,
 'next_activity': None}